[2024-11-05T14:34:08.140+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: initial_dag.name_node_task manual__2024-11-05T14:34:07.153882+00:00 [queued]>
[2024-11-05T14:34:08.147+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: initial_dag.name_node_task manual__2024-11-05T14:34:07.153882+00:00 [queued]>
[2024-11-05T14:34:08.147+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-11-05T14:34:08.157+0000] {taskinstance.py:1382} INFO - Executing <Task(SSHOperator): name_node_task> on 2024-11-05 14:34:07.153882+00:00
[2024-11-05T14:34:08.165+0000] {standard_task_runner.py:57} INFO - Started process 359 to run task
[2024-11-05T14:34:08.167+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'initial_dag', 'name_node_task', 'manual__2024-11-05T14:34:07.153882+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/initial-dag.py', '--cfg-path', '/tmp/tmpcu0h6ro_']
[2024-11-05T14:34:08.168+0000] {standard_task_runner.py:85} INFO - Job 4: Subtask name_node_task
[2024-11-05T14:34:08.223+0000] {task_command.py:416} INFO - Running <TaskInstance: initial_dag.name_node_task manual__2024-11-05T14:34:07.153882+00:00 [running]> on host 63a05eb89395
[2024-11-05T14:34:08.325+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='initial_dag' AIRFLOW_CTX_TASK_ID='name_node_task' AIRFLOW_CTX_EXECUTION_DATE='2024-11-05T14:34:07.153882+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-05T14:34:07.153882+00:00'
[2024-11-05T14:34:08.326+0000] {ssh.py:152} INFO - Creating ssh_client
[2024-11-05T14:34:08.326+0000] {ssh.py:300} WARNING - No Host Key Verification. This won't protect against Man-In-The-Middle attacks
[2024-11-05T14:34:08.333+0000] {transport.py:1893} INFO - Connected (version 2.0, client OpenSSH_7.4p1)
[2024-11-05T14:34:08.432+0000] {transport.py:1893} INFO - Authentication (password) successful!
[2024-11-05T14:34:08.432+0000] {ssh.py:478} INFO - Running command: ls && ls -al && pwd && ip -a && echo "Ovdje sam!"
[2024-11-05T14:34:08.489+0000] {ssh.py:524} INFO - total 28
[2024-11-05T14:34:08.490+0000] {ssh.py:524} INFO - drwx------ 1 root root 4096 Nov  5 14:33 .
[2024-11-05T14:34:08.490+0000] {ssh.py:524} INFO - drwxr-xr-x 1 root root 4096 Nov  5 14:12 ..
[2024-11-05T14:34:08.490+0000] {ssh.py:524} INFO - -rw------- 1 root root   10 Nov  5 14:33 .bash_history
[2024-11-05T14:34:08.490+0000] {ssh.py:524} INFO - -rw-r--r-- 1 root root  570 Jan 31  2010 .bashrc
[2024-11-05T14:34:08.490+0000] {ssh.py:524} INFO - drwx------ 1 root root 4096 Feb  4  2020 .gnupg
[2024-11-05T14:34:08.490+0000] {ssh.py:524} INFO - -rw-r--r-- 1 root root  148 Aug 17  2015 .profile
[2024-11-05T14:34:08.490+0000] {ssh.py:524} INFO - -rw------- 1 root root  850 Nov  5 14:29 .viminfo
[2024-11-05T14:34:08.490+0000] {ssh.py:524} INFO - /root
[2024-11-05T14:34:08.491+0000] {ssh.py:529} WARNING - Usage: ip [ OPTIONS ] OBJECT { COMMAND | help }
[2024-11-05T14:34:08.491+0000] {ssh.py:529} WARNING -        ip [ -force ] -batch filename
[2024-11-05T14:34:08.491+0000] {ssh.py:529} WARNING - where  OBJECT := { link | address | addrlabel | route | rule | neigh | ntable |
[2024-11-05T14:34:08.491+0000] {ssh.py:529} WARNING -                    tunnel | tuntap | maddress | mroute | mrule | monitor | xfrm |
[2024-11-05T14:34:08.491+0000] {ssh.py:529} WARNING -                    netns | l2tp | fou | macsec | tcp_metrics | token | netconf | ila }
[2024-11-05T14:34:08.492+0000] {ssh.py:529} WARNING -        OPTIONS := { -V[ersion] | -s[tatistics] | -d[etails] | -r[esolve] |
[2024-11-05T14:34:08.492+0000] {ssh.py:529} WARNING -                     -h[uman-readable] | -iec |
[2024-11-05T14:34:08.492+0000] {ssh.py:529} WARNING -                     -f[amily] { inet | inet6 | ipx | dnet | mpls | bridge | link } |
[2024-11-05T14:34:08.492+0000] {ssh.py:529} WARNING -                     -4 | -6 | -I | -D | -B | -0 |
[2024-11-05T14:34:08.492+0000] {ssh.py:529} WARNING -                     -l[oops] { maximum-addr-flush-attempts } | -br[ief] |
[2024-11-05T14:34:08.492+0000] {ssh.py:529} WARNING -                     -o[neline] | -t[imestamp] | -ts[hort] | -b[atch] [filename] |
[2024-11-05T14:34:08.492+0000] {ssh.py:529} WARNING -                     -rc[vbuf] [size] | -n[etns] name | -a[ll] |Â -c[olor]}
[2024-11-05T14:34:08.531+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/ssh/operators/ssh.py", line 191, in execute
    result = self.run_ssh_client_command(ssh_client, self.command, context=context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/ssh/operators/ssh.py", line 179, in run_ssh_client_command
    self.raise_for_status(exit_status, agg_stderr, context=context)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/ssh/operators/ssh.py", line 173, in raise_for_status
    raise AirflowException(f"SSH operator error: exit status = {exit_status}")
airflow.exceptions.AirflowException: SSH operator error: exit status = 255
[2024-11-05T14:34:08.534+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=initial_dag, task_id=name_node_task, execution_date=20241105T143407, start_date=20241105T143408, end_date=20241105T143408
[2024-11-05T14:34:08.545+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 4 for task name_node_task (SSH operator error: exit status = 255; 359)
[2024-11-05T14:34:08.580+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-11-05T14:34:08.601+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
